name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  prepare:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare data
        run: python model_G.py prepare

  train:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Train model
        run: python model_G.py train

  validate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate model
        run: python model_G.py validate
